<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WIN-3QS5O4QR69E" name="pe.com.test.seleniumwd.CategoriaWebDriverTest" tests="6" failures="1" timestamp="6 Mar 2017 04:09:02 GMT" time="58.666" errors="0">
  <testcase name="insertarCategoria" time="11.821" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest">
    <failure type="java.lang.AssertionError" message="expected [Se guardó de manera correcta la Categoría] but found [Mensaje incorrecto]">
      <![CDATA[java.lang.AssertionError: expected [Se guardó de manera correcta la Categoría] but found [Mensaje incorrecto]
	at org.testng.Assert.fail(Assert.java:94)
	at pe.com.test.seleniumwd.CategoriaWebDriverTest.insertarCategoria(CategoriaWebDriverTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- insertarCategoria -->
  <testcase name="insertarCategoria" time="9.227" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="insertarCategoria" time="9.378" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="insertarCategoria" time="9.396" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="insertarCategoria" time="9.517" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
  <testcase name="insertarCategoria" time="9.327" classname="pe.com.test.seleniumwd.CategoriaWebDriverTest"/>
</testsuite> <!-- pe.com.test.seleniumwd.CategoriaWebDriverTest -->
